-- CREO LA BASE DE DATOS
create database INSTITUTO;
-- USAR LA BASE DE DATOS
USE INSTITUTO;

DROP TABLE ASIGNATURA;
-- TABLA ALUMNO
-- ALUMNO (NIF,nombre,ap1,ap2)
CREATE TABLE ALUMNO (
    NIF VARCHAR(9), -- PRIMARY KEY
    nombre VARCHAR(150) NOT NULL,
    ap1 VARCHAR(150) NOT NULL,
    ap2 VARCHAR(150) NOT NULL,
    instituto VARCHAR (150) NOT NULL default 'IES Augustobriga',
    CONSTRAINT PK_ALUMNO PRIMARY KEY (NIF)
);

-- TABLA ASIGNATURA
-- ASIGNATURA (ID_Asignatura,nombreAsignatura,credito)
CREATE TABLE ASIGNATURA (
    ID_Asig INT,  -- PRIMARY KEY
    nombreAsignatura VARCHAR(150) NOT NULL,
    credito TINYINT UNSIGNED NOT NULL ,  -- UNSIGNED => SIEMPRE POSITIVO
    CONSTRAINT PK_ASIGNATURA PRIMARY KEY (ID_Asig)
);

-- CALIFICACION (NIF,ID_Asignatura,fecha,nota)
CREATE TABLE CALIFICACION (
    NIF_NOTA VARCHAR(9),
    ID_Asignatura INT,
    fecha DATE,
    nota DECIMAL(4 , 2 ) UNSIGNED NOT NULL,
    CONSTRAINT PK_CALIFICACION PRIMARY KEY (NIF_NOTA , ID_Asignatura , fecha),
    CONSTRAINT FK_NIF_NOTA_ALUMNO FOREIGN KEY (NIF_NOTA) REFERENCES ALUMNO (NIF),
    CONSTRAINT FK_ID_Asignatura_ASIGNATURA FOREIGN KEY (ID_Asignatura) REFERENCES ASIGNATURA ( ID_Asig)
);